name: Lambda API Deploy
on:
  push:
    branches: [ Master, master, main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create venv
        run: python -m venv venv

      - name: Activate venv and Install Dependencies
        run: source venv/bin/activate && pip install -r requirements/requirements.txt --ignore-installed

      - name: Zip
        run: (zip -r lambda-api.zip .)

      - name: Deploying lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: lambda-tech-challenge-api
          zip_file: ./lambda-api.zip
